# CODIGOS GIT

# AJUDA

## GIT HELP
## GIT HELP ADD
## GIT HELP COMMIT
## GIT HELP <QUALQUEL_COMANDO_GIT>

# CONFIGURAÇÃO

## GIT CONFIG --GLOBAL USER.NAME "RENATAFRANCA12"
## GIT CONFIG --GLOBAL USER.EMAIL "USER@EMAIL.COM"
## GIT CONFIG --LIST

# REPOSITORIO LOCAL

## GIT INIT
## GIT STATUS
## GIT ADD MEU_ARQUIVO.TXT
## GIT ADD MEU_DIRETORIO
## GIT ADD .
## GIT ADD -F ARQUIVO_NO_GITIGNORE.TXT

# COMITAR ARQUIVO/DIRETORIO

## GIT COMMIT MEU_ARQUIVO.TXT
## GIT COMMIT MEU_ARQUIVO.TXT MEU_OUTRO_ARQUIVO.TXT
## GIT COMMIT MEUARQUIVO.TXT -M "MINHA MENSAGEM DE COMMIT"

# REMOVER ARQUIVO OU DIRETORIO

## GIT RM MEU_ARQUIVO.TXT
## GIT RM -R DIRETORIO

# VISUALIZAR HISTORICO

## GIT LOG
## GIT LOG -P -2
## GIT LOG --STAT

# DESFAZENDO OPERAÇÕES

## GIT CHECKOUT -- MEU-ARQUIVO.TXT
## GIT RESET HEAD MEU_ARQUIVO.TXT

# REPOSITORIO REMOTO

## GIT REMOTE
## GIT REMOTE -V
## GIT REMOTE ADD ORIGIN GIT@GITHUB:RENATAFRANCA12/REPOSITORIOTESTE
## GIT REMOTE SHOW ORIGIN


# ESSES SAO ALGUNS DOS CODIGOS DO GIT 

## CONSULTE A DOCUMENTAÇÃO GIT E BONS ESTUDOS
